### PR TITLE
Fix branch symbol

### LINKED ISSUE #28: missing branch symbol
This is how I see the branch symbol:

Captura desde 2022-08-06 14-27-38

Not sure what is the expected unicode symbol

If this works correctly for you maybe we can add some config depending on system.

This could be a good option:
 ⎇'

This is not show on my laptop (maybe is the one you use
 

0xe0a0

image

### PR DESCRIPTION
**Pull request by albfan**
fix #28

### CODE REVIEW

**Comment by troydm** [comment]
won't merge this as current default icon is NerdFonts icon by default which is probably most used custom icons font

**Comment by albfan** [comment]
What's the Unicode symbol? Any link to check what's going on?

**Comment by troydm** [comment]
@albfan https://www.nerdfonts.com/cheat-sheet type branch in search box

**Comment by albfan** [comment]
Yes it says e725 for me.

I installed and restart some apps and some show, some don't

Not sure how spread use nerd fonts is. If you need any PR about a fallback configuration (so this works out of the box, let me know

**Pull request closed without merging**
