### PR TITLE
Filter by vcs status 

### LINKED ISSUE #21: vcs integration by plugin
I'm maintainer of [albfan/nerdtree-git-plugin](https://github.com/albfan/nerdtree-git-plugin)

As you now [nerdtree plugin](https://github.com/scrooloose/nerdtree) is a project drawer with lot of traction.

Its plugin api allows to extend it easily as [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)

I forked nerdtree-git-plugin to allow it to hide files based on file status, and it is a primary plugin on my workflow

Sadly as you now NERDTree performs really bad and slow down all vim when project overpass tens of files.

I have ported your plugin to python3 #20 and it performs dawn fast, great! so I will port my plugin inside yours. Seems an easy task

Just want to know if you have interest on:

- Plugin system for easytree: so you can extend it for any other use
    - icons for dirs and files
    - custom formatters
    - show/hide nodes
    - custom sorting
    - adding virtual nodes (listing different unrelated dirs)
- Helping or designing vcs integration

I will get progress on my fork and try to push upstream, but if you want to define milestones or priorities that would help to ease the pushes

### PR DESCRIPTION
**Pull request by albfan**
Here implemented for git

it fixes #21

 Isolating isPathTouched() and Format_dir() and Format_file() new shortcut in a pluggable system easytree can be extended at will

For me this work as is, but can rework if you want to merge it.

Again, this works pretty fast, great!

### CODE REVIEW

**Comment by albfan** [comment]
This is rebased onto support python3, so better to merge that to see only differences from that.

I detect a minor fix about doc for '?' which was removed

**Comment by albfan** [comment]
rebased to include fi to filter ignored files by vcs

**Comment by troydm** [comment]
@albfan before merging I would like to try it out myself in order to understand every change you did, also regarding #21 could you please close the pull request if it's not necessary

**Comment by albfan** [comment]
Please do code review on changes, I will try to explain them.

I have edited #21 subject to reflect it's primary intention. Easytree is good as is, so will be cool to define some mechanism to extend it (hiding files and formatting how they are output).

vcs integration would be done through that mechanism

Please comment on #21 if you like the idea (I'm totally ok if you don't like it, just close it if so)

About this PR is a suggestion, that just works. I want to share it and discuss if it can help others to better manage its projects, as for me is an essential tool in my workflow.

**Comment by troydm** [comment]
@albfan one question regarding git plugin? could you move it's functionality to separate git.vim file so file structure would look like this autoload/plugin/git.vim and then add code that loads any plugins that are in plugin folder and automatically registers them so it would be clear for people to how to actually write their own plugins if they want so. and also please move easytree.py file to autoload/python2/easytree.py for logical consitency

**Comment by albfan** [comment]
Sounds great. Let me rework that

**Comment by albfan** [comment]
I'm revisiting this

**Comment by albfan** [comment]
I will add more color to it and maybe test suite

**Comment by albfan** [comment]
Ok, color is there.

Seems after rebase I cannot reopen this.

Everything is still a mess but I think to allow this to work as a plugin we need these concepts:

1. a global concept of flag (some mark you can add to a dir or file)
2. a global concept of visibility (to hide ignored files)
3. a call from InitializeNewTree to plugin api to refresh metainfo
4. a Format_file and Format_dir functions to paint dirs and files

All those concepts are there, is just a matter of split into:

1. changes to actual plugin
2. changes to provide git status plugin

**Pull request closed without merging**
